# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
      branches:
        - main
      paths:
        - src/data-registry/train.csv.dvc

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download NLTK resources
      run: |
        python -m nltk.downloader all
    - name: Setup DVC
      run: |
        dvc remote modify myremote --local gdrive_service_account_json_file_path src/credentials.json
        dvc pull
    - name: Retraining
      working-directory: ./src
      run: |
        python main.py
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
        NEPTUNE_PROJECT_NAME: ${{ secrets.NEPTUNE_PROJECT_NAME }}
    - name: Push new model to DVC
      working-directory: ./src
      run: |
        dvc push model_v1.pkl

